apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: rm
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: common
  values:
    existingSecret: rm-minio-root-credentials

    persistence:
      storageClass: managed-nfs-storage-retain

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
      path: /
      hosts:
        - minio.192.168.58.2.nip.io
      tls:
        - secretName: minio-tls
          hosts:
            - minio.192.168.58.2.nip.io

    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
      path: /
      hosts:
        - console.minio.192.168.58.2.nip.io
      tls:
      - secretName: minio-console-tls
        hosts:
          - console.minio.192.168.58.2.nip.io

    resources:
      requests:
        memory: 1Gi