apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rm-minio-bucket-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-minio-bucket-api
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    fullnameOverride: minio-bucket-api
    minIOServerEndpoint: https://minio.192.168.58.2.nip.io
    accessCredentials:
      secretName: rm-minio-root-credentials
