apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registration-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-registration-api
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    fullnameOverride: registration-api
    # image: # {}
      # repository: eoepca/rm-registration-api
      # pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      # tag: "1.3-dev1"

    ingress:
      enabled: true
      hosts:
        - host: registration-api-open.192.168.58.2.nip.io
          paths: ["/"]
      tls:
        - hosts:
            - registration-api-open.192.168.58.2.nip.io
          secretName: registration-api-tls

    # some values for the workspace API
    workspaceK8sNamespace: "rm"
    redisServiceName: "data-access-redis-master"
