apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-workspace-api
      version: 1.3.5
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    fullnameOverride: workspace-api
    # image: # {}
      # repository: eoepca/rm-workspace-api
      # pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      # tag: "latest"

    ingress:
      enabled: true
      hosts:
        - host: workspace-api-open.192.168.58.2.nip.io
          paths: ["/"]
      tls:
        - hosts:
            - workspace-api-open.192.168.58.2.nip.io
          secretName: workspace-api-tls

    # some values for the workspace API
    prefixForName: "develop-user"
    workspaceSecretName: "bucket"
    namespaceForBucketResource: "rm"
    # s3Endpoint: "https://cf2.cloudferro.com:8080"
    s3Endpoint: "https://minio.192.168.58.2.nip.io"
    s3Region: "RegionOne"
    harborUrl: "https://harbor.192.168.58.2.nip.io"
    harborUsername: "admin"
    harborPasswordSecretName: "harbor"
    umaClientSecretName: "rm-uma-user-agent"
    umaClientSecretNamespace: "rm"
    workspaceChartsConfigMap: "workspace-charts"
    bucketEndpointUrl: "http://minio-bucket-api:8080/bucket"
    pepBaseUrl: "http://workspace-api-pep:5576/resources"
    autoProtectionEnabled: "True"
