apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: um-identity-service
  namespace: um
  annotations:
    meta.helm.sh/release-name: um-identity-service
    meta.helm.sh/release-namespace: um
spec:
  chart:
    spec:
      chart: identity-service
      version: 1.0.16
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    volumeClaim:
      name: eoepca-userman-pvc
      create: false
    identity-keycloak:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: identity.keycloak.192.168.58.2.nip.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: identity-keycloak-tls-certificate
            hosts:
              - identity.keycloak.192.168.58.2.nip.io
    identity-postgres:
      volumeClaim:
        name: eoepca-userman-pvc
    identity-api:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: identity.api.192.168.58.2.nip.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: identity-api-tls-certificate
            hosts:
              - identity.api.192.168.58.2.nip.io
    identity-manager:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: identity.manager.192.168.58.2.nip.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: identity-manager-tls-certificate
            hosts:
              - identity.manager.192.168.58.2.nip.io
    identity-proxy:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: identity.proxy.192.168.58.2.nip.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: identity-proxy-tls-certificate
            hosts:
              - identity.proxy.192.168.58.2.nip.io
  timeout: 5m0s
  interval: 1m0s