apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: um-pdp-engine
  namespace: um
spec:
  chart:
    spec:
      chart: pdp-engine
      version: 1.1.12
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    # image:
      # tag: v1.0
      # pullPolicy: Always
    global:
      nginxIp: 192.168.58.2
      domain: auth.192.168.58.2.nip.io
    volumeClaim:
      name: eoepca-userman-pvc
      create: false

  timeout: 25m0s
  interval: 1m0s
