apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: um-user-profile
  namespace: um
spec:
  chart:
    spec:
      chart: user-profile
      version: 1.1.12
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    global:
      domain: auth.192.168.58.2.nip.io
      nginxIp: 192.168.58.2
    volumeClaim:
      name: eoepca-userman-pvc
      create: false
  timeout: 25m0s
  interval: 1m0s
